lvl1 = {
	"words": [
	 "introspection",
	 "philanthropist",
	 "antidote",
	 "strive",
	 "ambidextrous",
	 "precursors",
	 "retrospective",
	 "introvert",
	 "ambiguous",
	 "gerontocracy",
	 "aggravate",
	 "braggart",
	 "entice",
	 "equilibrium",
	 "alleviate",
	 "adorn",
	 "malevolent",
	 "connote",
	 "abhor",
	 "agile",
	 "endeavor",
	 "stray",
	 "renovate",
	 "curriculum",
	 "amalgamate",
	 "drowsiness",
	 "disrobe",
	 "xenophile",
	 "suffocate",
	 "sequence",
	 "scent",
	 "sporadic",
	 "affinity",
	 "audacious",
	 "heterogeneous",
	 "animosity",
	 "fragile",
	 "acumen",
	 "legacy",
	 "massacre",
	 "submerge",
	 "combustion",
	 "adulteration",
	 "appease",
	 "premature",
	 "inquest",
	 "shunned",
	 "conceal",
	 "anguish",
	 "indigenous",
	 "apt",
	 "correlate",
	 "grumble",
	 "offhand",
	 "somersault",
	 "extinguish",
	 "edible",
	 "conjoin",
	 "surcharge",
	 "accolade",
	 "disallow",
	 "opaqueness",
	 "impermeable",
	 "console",
	 "timid",
	 "abscond",
	 "abide",
	 "embezzle",
	 "warrant",
	 "reminiscent",
	 "extinct",
	 "loll",
	 "acclaimed",
	 "clientele",
	 "catalyst",
	 "shallow",
	 "brittle",
	 "negligent",
	 "affable",
	 "poseur",
	 "dangle",
	 "moribund",
	 "ascend",
	 "relapse",
	 "asterisk",
	 "yarn",
	 "arrogance",
	 "salvage",
	 "livid",
	 "divergence",
	 "rejuvenation",
	 "allegiance",
	 "vigorous",
	 "dullard",
	 "dwarf",
	 "fragrant",
	 "judicious",
	 "nihilism",
	 "odor",
	 "scribble",
	 "hospitable",
	 "narcissism",
	 "sawdust",
	 "ameliorate",
	 "ingest",
	 "gait",
	 "sluggard",
	 "succumb",
	 "reiterate",
	 "flop",
	 "defer",
	 "ossified",
	 "eloquence",
	 "derivative",
	 "commuter",
	 "clot",
	 "weigh",
	 "steeply",
	 "torque",
	 "benefactor",
	 "complaisant",
	 "plea",
	 "moderation",
	 "enduring",
	 "invincible",
	 "sanity",
	 "turmoil",
	 "flimsy",
	 "tadpole",
	 "reconcile",
	 "cryptic",
	 "sponge",
	 "commemorate",
	 "sadistic",
	 "dote",
	 "encapsulate",
	 "fission",
	 "volatile",
	 "alloy",
	 "dormant",
	 "gallant",
	 "grievous",
	 "enzyme",
	 "shard",
	 "hypocrisy",
	 "eradicate",
	 "chisel",
	 "infuriate",
	 "engulf",
	 "euphoria",
	 "sanction",
	 "renowned",
	 "riddle",
	 "evoke",
	 "mischievous",
	 "implicit",
	 "disproof",
	 "misogynist",
	 "abysmal",
	 "writ",
	 "pertain",
	 "erratic",
	 "meticulous",
	 "impromptu",
	 "inclined",
	 "constrict",
	 "perish",
	 "lambaste",
	 "luminary",
	 "dupe",
	 "auxiliary",
	 "extralegal",
	 "ambivalent",
	 "tonic",
	 "endorse",
	 "turbulence",
	 "connoisseur",
	 "indistinct",
	 "abstruse",
	 "limp",
	 "parenthesis",
	 "sophisticated",
	 "aberration",
	 "recuperate",
	 "perjury",
	 "mite",
	 "pest",
	 "pluck",
	 "satiate",
	 "colloquial",
	 "yeoman",
	 "ail",
	 "fidelity",
	 "mesmerize",
	 "paradigm",
	 "gullible",
	 "sobriety",
	 "dislodge",
	 "fleet",
	 "articulate",
	 "tractable",
	 "partisan",
	 "predominate",
	 "foolproof",
	 "suffice",
	 "permeate",
	 "spear",
	 "solvent",
	 "presentiment",
	 "vivacious",
	 "coagulation",
	 "liberality",
	 "elaborate",
	 "brass",
	 "malleable",
	 "patron",
	 "immutable",
	 "forgery",
	 "woo",
	 "cordial",
	 "cumbersome",
	 "beguile",
	 "retrograde",
	 "sheath",
	 "bewilder",
	 "knit",
	 "unscathed",
	 "chortle",
	 "jabber",
	 "pivotal",
	 "implosion",
	 "repel",
	 "superimpose",
	 "centurion",
	 "enigma",
	 "calipers",
	 "redeem",
	 "buoyant",
	 "impede",
	 "stride",
	 "boisterous",
	 "resuscitation",
	 "concur",
	 "recitals",
	 "treacherous",
	 "indulgent",
	 "pilferer",
	 "foster",
	 "apartheid",
	 "garrulous",
	 "edify",
	 "evasive",
	 "misanthrope",
	 "eulogy",
	 "arcane",
	 "bogus",
	 "dexterity",
	 "lampoon",
	 "skit",
	 "incongruous",
	 "repulsive",
	 "refine"], 

	"meanings": [
	 "examining one's own thoughts and feelings",
	 "one who loves mankind",
	 "medicine used against a poison or a disease",
	 "to make great efforts",
	 "able to use the left hand or the right equally well",
	 "a person or thing that precedes",
	 "looking back on past",
	 "one who turns towards himself",
	 "doubtful; uncertain",
	 "government ruled by old people",
	 "make worse; irritate",
	 "boastful",
	 "attract",
	 "state of being balanced",
	 "make (pain) easier to bear",
	 "add beauty; decorate",
	 "malicious; evil; having or showing ill will",
	 "suggest or imply in addition to the precise",
	 "to hate; to detest",
	 "active; quick-moving",
	 "to make an effort",
	 "wander lose one's way",
	 "restore something to better condition",
	 "course of study",
	 "mix; combine; unite societies",
	 "feeling sleepy half asleep",
	 "undress",
	 "a person who is attracted to foreign peoples cultures",
	 "cause or have difficulty in breathing",
	 "succession connected line of",
	 "smell (especially pleasant)",
	 "happening from time to time",
	 "close connection; relationship",
	 "bold",
	 "made up of different kinds",
	 "strong dislike",
	 "easily injured broken or destroyed",
	 "keen",
	 "bequest or inheritance",
	 "cruel killing of a large number of people",
	 "put under water liquid sink out of sight",
	 "process of burning",
	 "making unpure; poorer in quality",
	 "make quiet or calm",
	 "doing or happening something before the right time",
	 "legal or judicial inquiry",
	 "avoided",
	 "hide keep secret",
	 "severe suffering",
	 "native",
	 "well-suited; quick-witted",
	 "have a mutual relation",
	 "to complain",
	 "without preparation or forethought",
	 "rolling backward or forward (not sideways) movement",
	 "end the existence of/wipe or put out",
	 "fit to be eaten/not poisonous",
	 "to join together",
	 "additional load/charge",
	 "praise; approval",
	 "refuse to allow or accept as a correct",
	 "dullness/not allowing light to pass through",
	 "that cannot be permeated",
	 "give comfort or sympathy to",
	 "shy easily frightened",
	 "to go away suddenly (to avoid arrest)",
	 "be faithful; to endure",
	 "use in a wrong way for one's own benefit",
	 "authority written order guarantee",
	 "suggest something in the past",
	 "no longer active",
	 "rest to sit or stand in a lazy way hang (dog's tongue)",
	 "welcomed with shouts and approval",
	 "customers",
	 "substance that causes speeding up",
	 "little depth; not earnest",
	 "easily broken",
	 "taking too little care",
	 "polite and friendly",
	 "a person who attempts to impress by acting unlike himself",
	 "hand or swing loosely",
	 "in a dying state; near death",
	 "go or come up",
	 "fall back again",
	 "the mark * (e.g.. omitted letters)",
	 "tale story fibers for knitting",
	 "proud; superior manner of behaviour",
	 "the saving of property from loss",
	 "furiously angry",
	 "getting farther apart from a point",
	 "becoming young in nature or appearance",
	 "duty support loyalty",
	 "strong energetic",
	 "a stupid",
	 "person much smaller the usual size",
	 "sweet-smelling",
	 "sound in judgment; wise",
	 "total rejection of all religious and moral beliefs",
	 "smell",
	 "write hastily",
	 "liking to give hospitality",
	 "self-love",
	 "tiny bits of wood",
	 "improve; make better",
	 "take in by swallowing",
	 "a manner of walking",
	 "lazy slow-moving person",
	 "yield",
	 "say or do again several times",
	 "fail/move/fall clumsily",
	 "postpone",
	 "turned to bone; hardened like bone; inflexible",
	 "fluent speaking skillful use of language",
	 "unoriginal; obtained from another source",
	 "person who travels regularly",
	 "half-solid lump formed from liquid",
	 "measure hoe heavy something is",
	 "rising or falling sharply",
	 "twisting force causing rotation",
	 "person who has given help",
	 "trying to please; obliging",
	 "request",
	 "quality of being limited; not extreme",
	 "lasting",
	 "too strong to be defeated",
	 "health of mind soundness of judgment",
	 "trouble disturbance",
	 "lacking solidarity",
	 "form of a frog when it leaves the egg",
	 "settle a quarrel restore peace",
	 "secret with a hidden meaning",
	 "porous rubber for washing live at once expense",
	 "keep the memory of",
	 "cruel",
	 "show much fondness center one's attention",
	 "enclose in capsule",
	 "splitting or division (esp. of cells)",
	 "changeable inconstant fickle unstable explosive",
	 "to debase by mixing with something inferior",
	 "in a state of inactivity but awaiting development",
	 "brave",
	 "causing grief or pain; serious dire grave",
	 "catalyst",
	 "a piece of broken pottery",
	 "falsely making oneself appear to be good",
	 "get rid of pull up by the roots",
	 "steel tool for shaping materials",
	 "fill with fury or rage",
	 "swallow up",
	 "elation state of pleasant excitement",
	 "approval (by authority) penalty",
	 "celebrated; famous",
	 "puzzling person or thing",
	 "call up bring out",
	 "harmful; causing mischief",
	 "implied though; not plainly expressed",
	 "proof to the contrary",
	 "one who hates women/females",
	 "extreme bad",
	 "written order",
	 "belong as a part have reference",
	 "irregular in behaviour or opinion",
	 "giving great attention to details",
	 "without preparation",
	 "directing the mind in a certain direction",
	 "make tight or smaller",
	 "be destroyed decay",
	 "attack verbally",
	 "star; light-giving body",
	 "cheat make a fool of",
	 "helping; supporting",
	 "outside the law",
	 "having both of two contrary meanings",
	 "something giving strength or energy",
	 "write one's name on the back of",
	 "being uncontrollably violent",
	 "a person with good judgement (e.g.. in art)",
	 "not easily heard; seen clearly marked",
	 "difficult to comprehend; obscure",
	 "lacking strength; walking unevenly",
	 "sentence within another one something separated",
	 "complex; subtle; refined",
	 "straying away from what is normal",
	 "become strong after illness loss exhaustion",
	 "willful false statement unlawful act",
	 "a very small amount",
	 "destructive thing or a person who is nuisance",
	 "pull the feathers off pick (e.g.. flowers)",
	 "satisfy fully",
	 "involving or using conversation.",
	 "man owning small estate; middle-class farmer",
	 "to cause pain",
	 "loyalty accuracy",
	 "hypnotize",
	 "a model example or pattern",
	 "easily gulled",
	 "quality or condition of being sober",
	 "move force from the place occupied",
	 "number of ships; quick-moving",
	 "speak distinctly; connect by joints",
	 "easily controlled or guided",
	 "one-sided committed to a party biased or prejudiced",
	 "have more power than others",
	 "incapable of failure or error",
	 "be enough",
	 "spread into every part of",
	 "weapon with a metal point on a long shaft",
	 "of the power of forming a solution",
	 "anticipatory fear; premonition",
	 "lively high-spirited",
	 "change to a thick and solid state",
	 "free giving; generosity",
	 "worked out with much care in great detail",
	 "yellow metal (mixing copper and zinc)",
	 "yielding easily shaped; moldable; adapting",
	 "regular customer person who gives support",
	 "that cannot be changed",
	 "counterfeit",
	 "try to win",
	 "warm and sincere",
	 "burdensome; heavy and awkward to carry",
	 "mislead or delude; cheat; pass time",
	 "receding",
	 "cover for the blade of a weapon or a tool",
	 "puzzle; confuse",
	 "draw together; unite firmly",
	 "unharmed unhurt",
	 "loud chuckle of pleasure or amusement",
	 "talk excitedly; utter rapidly",
	 "of great importance (others depend on it)",
	 "collapse; bursting inward",
	 "refuse to accept/cause dislike",
	 "put something on the top",
	 "leader of a unit of 100 soldiers",
	 "something that is puzzling",
	 "metal supports attached to the legs measuring instrument",
	 "get back by payment compensate",
	 "able to float; light-hearted",
	 "hinder; get in the way of",
	 "walk with long steps",
	 "noisy; restraint",
	 "coming back to consciousness",
	 "agree in opinion happen together",
	 "a number of performance of music",
	 "not to be trusted",
	 "inclined to indulge",
	 "to steal",
	 "nurture; care for",
	 "brutal racial discrimination",
	 "too talkative",
	 "instruct; correct morally",
	 "tending to evade",
	 "person who hates mankind",
	 "formal praise panegyric",
	 "known or understood by very few",
	 "sham; counterfeit; not genuine",
	 "skill (esp. in handling)",
	 "publicly mock or ridicule",
	 "short piece of humorous writing",
	 "out of place; not in harmony or agreement",
	 "causing a feeling of disgust",
	 "make or become pure"]
}